### ISSUE TITLE
Set_Carrier_Freq independend frequencies

### ISSUE THREAD

**Issue by paulh002** [WA2FZW/It-s-Not-Just-Another-Digital-VFO-by-WA2FZW-VK3PE-and-G3ZQC#1]
Hi, 
Is there any way to output different frequencies on clck1 and clck0 ? I would like to output 26 mhz and 9 mhz (bfo) frequency. By the way, vfo looks very good!. I tried it and works fine.

**Comment by WA2FZW** [comment]
The simple answer is yes, but it would take some serious modifications to the code as the Si5351 code is hand-crafted (by TJ, not me) as opposed to using a standard library.
 
You’ll have to read the Si5351 datasheet (which will really make your head hurt) and you might look at some of the example programs included in the Adafruit_Si5351_Library to see how to do it.
 
Good luck!
John

**Comment by paulh002** [comment]
Thanks, so no easy solution :). I will have a go at the datasheet.

**Comment by paulh002** [comment]
I have it working now, if you like I can share it. I had two options add some functionality with some limitations (it works for < 100Mhz) which is enough for me. But I also made a new i2c library which I can include in the etherkit_si5351 library. Which uses the build in but somehow does not function. Cheers Paul

**Comment by WA2FZW** [comment]
I  tried both the Etherkit and Adafruit Si5351 libraries with no success.

I'm not sure what you did based on your message, but if you want to 
elaborate send me a direct email  (good on QRZ).

JP

**Comment by paulh002** [comment]
I am new to qrz.com cannot get your e-mail, was not active in more than 30 years :), decided to build a transeiver and in need of a VFO. Build one based on esp32 and si5351 and Inspired by T.UEBO / JF3HZB. Anyway you can get the code from https://1drv.ms/u/s!Ap0-o26gdN7pjPI5fhf2OSHI2jg-EQ?e=YCUuNa (onedrive) I still have an issue with reading from i2c which I am still checking but stetting the si5351 works ok.  There are 2 versions one a adapted etherkit and one for your VFO.
